---
title: "Developing R packages"
output: html_notebook
---

```{r load packages , message = FALSE, warning=FALSE}
if(!require(devtools)){install.packages("devtools")}
if(!require(knitr)){install.packages("knitr")}
if(!require(ggplot2)){install.packages("roxygen2")}
if(!require(testthat)){install.packages("testthat")}

if(!require(dplyr)){install.packages("dplyr")}
if(!require(ggplot2)){install.packages("ggplot2")}
if(!require(purrr)){install.packages("purrr")}
if(!require(moments)){install.packages("moments")}

```


# ChAPtER 1 :: package management

```{r create package dir}
# Use the create function to set up your first package

if (!file.exists("mlhelper")){
   create("mlhelper")}

# Take a look at the files and folders in your package
dir("mlhelper")
```


```{r add function}
# What is in the R directory before adding a function?
dir("mlhelper/R")

# Use the dump() function to write the numeric_summary function
dump("numeric.summary", file = "mlhelper/R/numeric.summary.R")
dump("df.numeric.summary", file = "mlhelper/R/df.numeric.summary.R")

# Verify that the file is in the correct directory
dir("mlhelper/R")
```


```{r ex14}
#' mlhelper: Helper functions for EDA and ml
#'
#' Generate custom data frame summaries
#'
#' @docType package
#' @name mlhelper
"_PACKAGE"


```

```{r package documentation}
# Generate package documentation
document("mlhelper")

# Examine the contents of the man directory
dir("mlhelper/man")

# View the documentation for the numeric.summary function
help("numeric.summary")

# View the documentation for the weather dataset
help("df.numeric.summary")

```

```{r check}

check("mlhelper")

```



```{r add dependencies}
# Add dplyr as a dependency to the DESCRIPTION file
use_package("dplyr", pkg = "mlhelper")

# Add purrr as a dependency to the DESCRIPTION file
use_package("purrr", pkg = "mlhelper")

# Add tidyr as an imported dependency to the DESCRIPTION file
use_package("moments", pkg = "mlhelper")
```

```{r build the package}

# Build the package
build("mlhelper")

# Examine the contents of the current directory
dir()


```



# CHAPTER 2 :: functions
```{r numeric.summary}
# create numeric summary for a df$column in df format
numeric.summary <- function(x, na.rm) {
  
  # Include an error if x is not numeric
  if(!is.numeric(x)){
    stop("Data must be numeric")
  }
  
  # Create data frame
  data.frame( MIN = min(x, na.rm = na.rm),
              Q1 = quantile(x, 0.25, na.rm = na.rm),
              MEAN = round(mean(x, na.rm = na.rm),2),
              MEDIAN = round(median(x, na.rm = na.rm),2),
              Q3 = quantile(x, 0.75, na.rm = na.rm), 
              IQR = IQR(x, na.rm = na.rm),
              SD = round(sd(x, na.rm = na.rm),2),
              MAX = max(x, na.rm = na.rm),
              SKEWNESS = round(skewness(x, na.rm = na.rm),2))%>%
    mutate(SKEW = ifelse(MEAN > MEDIAN, "RIGHT", "LEFT"))
}
```


```{r}
numeric.summary(iris$Sepal.Length, na.rm=TRUE)
```

```{r df.numeric.summary}

df.numeric.summary <- function(x, na.rm = TRUE){
  
  df.numeric <- select_if(x, .predicate = is.numeric) 
  
  map_df(df.numeric, .f = numeric.summary, na.rm = TRUE, .id = "ID")
  
}

```

```{r}
df.numeric.summary(iris, na.rm = TRUE)
```

# CHAPTER 3 :: loading the package

```{r load from local}
library(mlhelper, lib.loc = "e:/RProjects/packages")
```

```{r invoke functions}
mlhelper::df.numeric.summary(iris)
```

```{r install from github}
install_github("szintakacseva/mlhelper")
library(mlhelper)

df.numeric.summary(iris)

```

